### ISSUE TITLE
Add Visa Electron support

### ISSUE THREAD

**Issue by jo11yn** [cholojuanito/credit_card_validator#8]
Hello,

i'm currently using your lib for a project and i'm missing Visa Electron support. Would you be ok i i try to contribute to your lib by trying to create a pull request dealing with this ?

Best regards

**Comment by cholojuanito** [comment]
Certainly! I'm just following the supported cards from Braintree's parent repo that is written in JavaScript but any help is always welcome

**Comment by cholojuanito** [comment]
Although I will say, I think that everything Visa starts with a 4 so I would think that Visa Electron is supported since it is issued by Visa

**Comment by jo11yn** [comment]
Thanks for your feedback. Turns out i was using https://ccard-generator.com/generate-card/visa-electron to tests cards but their number don't pass the Luhn algorithm despite saying so.

But after some tests on real cards they are indeed detected as Visa Card so all good for me.

I'm closing this issue sorry for the inconvenience and thanks for this lib 👍
